version: 2.1

orbs:
  check: cloudify/wagon-bulder-orb@volatile

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello wowwaaa"
      - run: echo aaa
